config/routes.rb
Rails.application.routes.draw do
  get 'users/home'
  get 'users/login'
	root 'static_pages#home'
  get 'static_pages/home'
  resources :gossips do
    resources :comments, only: [:new, :create, :show, :index, :destroy]
  end
  get 'users/home' => 'users#home'
  get 'users/login' => 'users#login'
  post 'users/login' => 'users#check'
  get 'users/new' => 'users#new'
  post 'users/new' => 'users#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user, optional: true
  #has_and_belongs_to_many :tags
  has_many :comments
  #has_many :likes 
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  before_action :set_current_user

  private

  def set_current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		@comment = Comment.new
	end

	def create
		paracomm = params[:comment]
		puts "ceci est params[:comment] dans la méthode create commentaire : #{paracomm}"
		@gossip = Gossip.find(params[:gossip_id])
#		puts @gossip
		@comment = @gossip.comments.create(content: paracomm[:content] )

		puts @comment
		redirect_to gossip_comment_path(@gossip, @comment)
		#action:gossip_comment_path, id:1
	end

	def show
		@gossip = Gossip.find(params[:gossip_id])

		return @comment
		@commentaire = Comment.find(id: params[:comment_id])

		#Couldn't find Comment with 'id'={:gossip_id=>"1"}
	end

	def index
		@comment = Comment.all
	end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	def new
		@gossip = Gossip.new
		#@comment = Comment.new
		#session[:current_user_id] = @user.id
	end

	def create
		gossip = params[:gossip]
		@gossip = Gossip.create!(content: gossip[:content])

		redirect_to @gossip
	end

	def show
		@gossip = Gossip.find(params[:id])
		puts session[:current_user_id]
	end

	def edit
		@gossip = Gossip.find(params[:id])
	end

	def update
	  @gossip = Gossip.find(params[:id])

		gossip_params = params.require(:gossip).permit(:anonymous_gossiper, :content)
		@gossip.update(gossip_params)

		redirect_to gossips_path
	end

	def index
		@gossip = Gossip.all
	end

	def destroy
		@gossip = Gossip.find(params[:id])
		@gossip.destroy
		redirect_to gossips_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def home
    # if session[:user_id]
    #   @current_user = User.find(session[:user_id])
    # end
    
    #set_current_user
  end


	def login
	  session[:test] = "Valeur de test"
	end

  def check
    @current_user = User.where(name: params[:name], password: params[:password]).first
    if @current_user
      session[:user_id] = @current_user.id
      flash[:info] = "Vous êtes maintenant connecté"
      redirect_to "/users/home"
    else
      session[:user_id] = nil
      flash[:info] = "Échec de la connexion"
      redirect_to "/users/login"
    end
  end

  def new
  	@user = User.new
  end

  def create
  	user = params[:user]
  	@user = User.create!(name: user[:name], password: user[:password])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<!-- create.html.erb -->

app/views/comments/index.html.erb
<% @comment.each do |f| %>
	<div>
		<%= @comment.content %>
	</div>
<% end %>

app/views/comments/new.html.erb
	<%= form_for @comment, url: {action: "create"}, html: {:class => 'form-group'} do |f| %> 

		<%= f.text_area :anonymous_commentor, size: "5em", class: 'form-control', placeholder: 'auteur' %> <br>
		<%= f.text_area :content, size: "5em", class: 'form-control', placeholder: 'ton commentaire' %> <br>


		<%= f.submit "Create" %>
	<% end %>

app/views/comments/show.html.erb
<h2>Tous les commentaires de cette info!</h1>

<p>info : "<%= @gossip.content %>"</p>

<% @gossip.comments.each do |comment| %>
	<%= comment.anonymous_commentor %>
	<p><%= comment.content %><p><br>
<% end %>

app/views/gossips/create.html.erb
<!-- <p>salut, voici ton ragot</p>
<%# @gossip.content %> -->

app/views/gossips/edit.html.erb
<h1>coucou ça va</h1>

<%= form_for @gossip do |f| %>
	<div class="form-group">
	
		<%= f.text_field :anonymous_gossiper, placeholder: 'change ton nom' %>
	</div>

	<div class="form-group">
	<%= f.text_field :content, class: 'form-control', placeholder: 'modifie l\'info' %>
	</div>

	<div class="form-group">
		<%= f.submit "Modifier l'info" %>
	</div>
	

<% end %>

app/views/gossips/index.html.erb
<h1>salut</h1>


<% @gossip.each do |gossip| %>

	<div class="card" style="90%;">
  		
  			<div class="card-body">
    			<h5 class="card-title"> <%= gossip.anonymous_gossiper %></h5>
    			<p class="card-text"><%= "a écrit : \"#{gossip['content']}\"" %></p>
    			
    			<%= link_to "page de cette info", gossip_path(gossip.id), class: "btn btn-lg btn-light" %>

    			<%= link_to "modifier", edit_gossip_path(gossip.id), class: "btn btn-lg btn-dark" %>
    			<%= link_to "supprimer", gossip_path(gossip.id), class: "btn btn-danger", :data => {:confirm => 'Are you sure?', :method => "DELETE"} %>
  			</div>
	</div>
	<br>

<% end %>

app/views/gossips/new.html.erb
<div>
	<%# if session[:current_user_id] != nil %>

		<%= form_for @gossip, url: {action: "create"}, html: {:class => 'form-group'} do |f| %> 

			<%= f.text_area :anonymous_gossiper, size: "5em", placeholder: 'ton blaze?' %> <br>
			<%= f.text_area :content, size: "5em", class: 'form-control', placeholder: 'balance ton info' %> <br>

			<%= f.submit "Create" %>
		<% end %>
	<%# else %>
		<!-- <p>prière de te connecter pour poster un gossip! (ou revenir à l'accueil pour s'enregistrer)</p><a href="../users/login">se connecter</a> -->
	<%# end %>
</div>

app/views/gossips/show.html.erb
<!-- afficher
lien pour éditer
lien pour afficher tous -->

<%= link_to "toutes les infos", gossips_path, class: "btn btn-lg btn-primary" %>

<%=  session[:current_user_id] %> 

<div class="card" style="width: 20rem;">
	<div class="card-body">
    	<h5 class="card-title">salut, voici ton info!</h5>
    		<p class="card-text">Anonymous a écrit :</p>
    		<em>"<%= @gossip.content %>"</em>
    		<!-- <a href="/potin/<%#gossip[:id]%>">page de ce potin</a> -->
  	</div>
  	<%= link_to "modifier", edit_gossip_path, class: "btn btn-secondary" %>
  	<%= link_to "commenter", new_gossip_comment_path(params[:id]), class: "btn btn-success" %>

<!-- 

<div>
</div>

 -->
  	<%# @comment %>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-custom">
  <div class="container-fluid d-inline-flex">

    <button type="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navbarSupportedContent" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="navbar-toggler-icon"></span>
      <a class="navbar-brand justify-content-start" href="#">caca</a>
    </button>

    <!-- <a class="navbar-brand justify-cotent-start" href="#">caca<%# image_tag "logo.png", size:"50" %></a> -->
    <%= link_to "Accueil", root_path, class: "navbar-brand justify-content-start" %>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="nav navbar-nav ml-auto" style="float: right">
        <li class="nav-item"><%= link_to "balance!", new_gossip_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "toutes les infos!", gossips_path, class: "nav-link" %></li>
        <li class="nav-item">soon<%# link_to "balance!", new_gossip_path, class: "nav-link" %></li>
        <li class="nav-item">soon<%# link_to "balance!", new_gossip_path, class: "nav-link" %></li>
        <li class="nav-item">soon<%# link_to "balance!", new_gossip_path, class: "nav-link" %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipS5breg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="https://getbootstrap.com/docs/4.0/examples/album/album.css">
    <!-- <link rel="stylesheet" type="text/css" href="https://getbootstrap.com/docs/3.3/dist/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="https://getbootstrap.com/docs/3.3/examples/theme/theme.css"> -->

    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


  </head>

  <body>

    <%= render partial: "layouts/header" %>
    <div class="container-fluid">
      <br>
      <div><%= flash[:info] %></div>
      <div><%= session[:current_user_id]%></div>
      <br>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue sur la home !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <a href="users/new">Enregistre-toi !</a>
  <a href="users/login">Connecte-toi !</a>
  <%# link_to "Enregistre-toi !", 'link_to ', class: "btn btn-lg btn-primary" %>
</div>

app/views/users/home.html.erb
<h1>Bienvenue dans la home !</h1>


<% if @current_user %>
  <p>Tu es bien connecté en tant que : <%= @current_user.name %> </p>
<% else %>
  <h2>Bienvenue utilisateur non-enregistré :)</h2>
  <a href="/users/login">S'identifier</a>
<% end %>

app/views/users/login.html.erb
<h1>Connexion</h1>
<a href="/users/home">Retourner à l'accueil</a>
<%= form_tag "/users/login", method: :post do %>
  <input type="text" name="name" />
  <input type="password" name="password" />
  <input type="submit" value="Se connecter" />
<% end %>

app/views/users/new.html.erb
<h2>s'enregistrer</h2>

<%= form_for @user, url: {action: "create"}, html: {:class => 'form-group'} do |t| %>
	<%= t.text_field :name, placeholder: "ton nom"  %>
	<%= t.text_field :password, placeholder: "choisis un mot de passe"  %>
	<%= t.submit "Create" %>

<% end %>